In [1]:
# NumPy

In [2]:
%pip install numpy


[notice] A new release of pip available: 22.3 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
# Array is a powerful grid used to store a collection of data—usually numbers—where every item is of the same type.

In [5]:
# An array is a data structure consisting of a collection of elements of the same data type, stored in 
# contiguous memory locations and identified by at least one array index or key

In [6]:
# Creating Arrays

In [7]:
# 1D Array (also known as a Vector).

In [8]:
sample_array = np.array([1, 2, 3, 4])

In [9]:
sample_array

array([1, 2, 3, 4])

In [10]:
# 2D Array (a matrix) with 2 rows and 2 columns.

In [11]:
sample_array_2 = np.array([[1, 2], [3, 4]])

In [12]:
sample_array_2

array([[1, 2],
       [3, 4]])

In [13]:
# 3D tensor is a collection of 2D matrices stacked together, 
# represented in NumPy as a nested array with three axes: depth, rows, and columns.

In [14]:
# 3D Tensor (2 matrices, each with 2 rows and 2 columns)

In [15]:
sample_tensor_3 = np.array([
    [[1, 2], [3, 4]], # First matrix
    [[5, 6], [7, 8]]  # Second matrix
])

In [16]:
sample_tensor_3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [17]:
# Array Properties

In [18]:
sample_array = np.array([[1,2,3],[4,5,6]])

In [19]:
sample_array.shape # (rows, columns)

(2, 3)

In [20]:
# Dimension (also called an axis) refers to the number of directions needed to find a specific piece of data.

# 0-D Array (Scalar): A single number (e.g., 5). It has no dimensions.
# 1-D Array (Vector): A simple list of numbers (e.g., [1, 2, 3]). You only need one index to find a value.
# 2-D Array (Matrix): A table with rows and columns. You need two indices (row, column) to find a value.
# 3-D Array (Tensor): A stack of tables (like a book of spreadsheets). You need three indices (page, row, column) to find a value. 


In [21]:
sample_array.ndim # dimensions

2

In [22]:
sample_array.size # total elements

6

In [23]:
sample_array.dtype # data type

dtype('int64')

In [24]:
# Special Arrays

In [25]:
np.zeros((2,3))   # all zer

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones((2,3))    # all ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.arange(0,10,2) # range

array([0, 2, 4, 6, 8])

In [28]:
# np.arange(start, stop, step)
# Focuses on the interval between numbers.
# Result: [0, 2, 4, 6, 8]
# Behavior: Similar to Python's range. It starts at 0 and adds 2 repeatedly. It excludes the stop value (10).
# Best Use: When you know exactly how far apart you want your numbers to be.

In [29]:
np.linspace(0,1,5) # equally spaced values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [30]:
# np.linspace(start, stop, num)
# Focuses on the total count of numbers.
# Result: [0. , 0.25, 0.5 , 0.75, 1. ]
# Behavior: "Linear Space." It squeezes exactly 5 numbers between 0 and 1. It includes the stop value (1) by default.
# Best Use: When you need a specific number of points to create a smooth line or graph.

In [31]:
# Indexing & Slicing

In [32]:
sample_array = np.array([10,20,30,40])

In [33]:
sample_array[0]     # first element

np.int64(10)

In [34]:
sample_array[1:3]   # slicing
# The simplest way to remember slicing is: [Start : Stop before]

array([20, 30])

In [35]:
# 2D indexing

In [36]:
sample_array = np.array([[1,2,3],[4,5,6]])

In [37]:
sample_array[0,1]   # row 0, col 1

np.int64(2)

In [38]:
# Array Operations

In [39]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [40]:
a + b

array([5, 7, 9])

In [41]:
a - b

array([-3, -3, -3])

In [42]:
a * b

array([ 4, 10, 18])

In [43]:
a / b

array([0.25, 0.4 , 0.5 ])

In [44]:
# Mathematical Functions

In [45]:
sample_array = np.array([1,4,9])

In [46]:
np.sqrt(sample_array)

array([1., 2., 3.])

In [47]:
# In NumPy, exponential refers to raising the constant e𝑒
# (Euler's number, approximately 2.718) to the power of each element in your array.

In [48]:
np.exp(sample_array)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03])

In [49]:
np.log(sample_array)

array([0.        , 1.38629436, 2.19722458])

In [50]:
# Statistical Functions

In [51]:
sample_array = np.array([1,2,3,4,5])

In [52]:
np.mean(sample_array)

np.float64(3.0)

In [53]:
np.median(sample_array)

np.float64(3.0)

In [54]:
np.std(sample_array)

np.float64(1.4142135623730951)

In [55]:
np.sum(sample_array)

np.int64(15)

In [56]:
np.min(sample_array)

np.int64(1)

In [57]:
np.max(sample_array)

np.int64(5)

In [58]:
# Reshaping Arrays

In [59]:
# np.arange() generates an array of evenly spaced values within 
# a given interval, defined by a start (inclusive), stop (exclusive), and an optional step size.

In [60]:
sample_array = np.arange(6)

In [61]:
sample_array

array([0, 1, 2, 3, 4, 5])

In [62]:
reshaped = sample_array.reshape(2,3)

In [63]:
reshaped

array([[0, 1, 2],
       [3, 4, 5]])

In [64]:
# Flattening

In [65]:
sample_array = np.array([[1,2],[3,4]])

In [66]:
sample_array

array([[1, 2],
       [3, 4]])

In [67]:
sample_array.flatten()

array([1, 2, 3, 4])

In [68]:
# Joining Arrays

In [69]:
a = np.array([1,2])

In [70]:
b = np.array([3,4])

In [71]:
np.concatenate((a,b))

array([1, 2, 3, 4])

In [72]:
# Splitting Arrays

In [73]:
sample_array = np.array([1,2,3,4])

In [74]:
np.array_split(sample_array, 2)

[array([1, 2]), array([3, 4])]

In [75]:
# Sorting

In [76]:
sample_array = np.array([3,1,2])

In [77]:
np.sort(sample_array)

array([1, 2, 3])

In [78]:
# Searching

In [79]:
sample_array = np.array([1,2,3,4])

In [80]:
np.where(sample_array == 3)

(array([2]),)

In [81]:
# Random Module

In [82]:
np.random.rand(3)       # random floats

array([0.02380918, 0.32747256, 0.20799427])

In [83]:
np.random.randint(1,10,5) # random integers

array([3, 9, 4, 8, 3])

In [84]:
# Axis Concept

In [85]:
# In NumPy, Axis is just another word for Dimension. 
# You use axes to tell NumPy which direction to perform a calculation (like summing numbers).

In [86]:
sample_array = np.array([[1,2],[3,4]])

In [87]:
np.sum(sample_array, axis=0)  # column-wise

array([4, 6])

In [88]:
np.sum(sample_array, axis=1)  # row-wise

array([3, 7])

In [89]:
# NaN & Missing Values

In [90]:
# In NumPy, NaN stands for "Not a Number". 
# It is a special floating-point value used to represent missing or undefined data.

In [91]:
sample_array = np.array([1, np.nan, 3])

In [92]:
np.isnan(sample_array)

array([False,  True, False])

In [93]:
np.nanmean(sample_array)

np.float64(2.0)

In [94]:
# This code calculates the average of an array while ignoring any missing values (NaN).
# How it works:
# The Problem: If you use the regular np.mean(), any NaN in the data "breaks" the math, and the result will just be nan.
# The Fix: np.nanmean() treats the "holes" as if they don't exist. 
# It sums the available numbers and divides by the count of actual numbers (not the total size of the array).